version: "3.8"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "100"


services:

  app:
    <<: *logging
    command: [ "air", "-c", "/app/.docker/.air.toml", "--", "-h" ]
    container_name: test_mail_backend_app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - .env

  postgres:
    <<: *logging
    container_name: test_mail_backend_postgres
    image: postgres:13.1-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "LANG=en_US.UTF-8"
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"

volumes:
  postgres_data: